# Site
repository: sproogen/modern-resume-theme
# favicon: images/favicon.ico

version: 2

# Personal info
name: Foteini
title: Product Designer
email: fotini@email.com
darkmode: false

# Social links
github_username: ""
linkedin_username: ""

# About Section
about_profile_image: images/avatar.png
about_content: |
  Enthusiastic UI/UX Designer.

content:
  
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Novibet
        sub_title: Product Designer
        caption: May 2025 - Present
        description: |
          Designed end-to-end user experiences for web and mobile platform

      - layout: left
        title: Core Group
        sub_title: UI/UX Designer
        caption: Sept 2022 - Apr 2025
        description: |
          Designed end-to-end user experiences for web and mobile platform

      - layout: left
        title: MMA Architects
        sub_title: Architect
        caption: Sept 2021 - Aug 2022
        description: |
          Designed end-to-end user experiences for web and mobile platform
          
  - title: Certifications
    layout: list
    content:
      - layout: left
        #border: weak
        title: Google UX Design Certificate
        #link_text: Link Text
        #additional_links:
          #- title: Github page for project
            #icon: fab fa-github
            #url: https://github.com/example
        #quote: >
          #Short overview of the project
        description: |
         Completed training designed for entry-level job readiness. Topics included UX research fundementals, inclusive design, wireframes, low and high-fidelity prototypes.
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: MSc in Human-Computer Interaction
        sub_title: University of Patras

      - layout: top-left
        title: Integrated Master in Architecture Engineering
        sub_title: Aristotle University of Thessaloniki

  - title: Skills
    layout: text
    content: |
      Figma • Adobe XD • Autocad • Rhino 3D • Adobe Photoshop • Adobe Indesign • HTML • CSS

      

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme
# remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"

