# Site
repository: sproogen/modern-resume-theme
# favicon: images/favicon.ico

version: 2

# Personal info
name: Foteini Ypsilanti
title: Product Designer
email: fotini@email.com
darkmode: false

# Social links
github_username: ""
linkedin_username: ""

# About Section
about_profile_image: images/avatar.png
about_content: |
  Enthusiastic Product Designer with a passion for creating intuitive and engaging user experiences across web and mobile platforms.
  Skilled in translating complex problems into design solutions. Experienced in collaborating with cross-functional teams to deliver user-centered products that align with business goals.
  
content:
  
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Product Designer
        sub_title: Novibet
        caption: May 2025 - Present
        description: |
          - Designed end-to-end user experiences for web and mobile platform
          - Developed wireframes, interactive prototypes, and design mockups through collaborative brainstorming sessions
          - Collaborated with cross-functional teams (PMs, developers, marketing) to align design solutions with business goals
          - Ensured accessibility, responsive design, and seamless experiences across devices

      - layout: left
        title: UI/UX Designer
        sub_title: Core Group
        caption: Sept 2022 - Apr 2025
        description: |
          - Redesigned the product platform to enhance overall user experience and engagement
          - Conducted user research and usability testing to uncover pain points and refine design solutions
          - Collaborated closely with developers to ensure design feasibility, consistency, and implementation quality across platforms
         

      - layout: left
        title: Architect
        sub_title: MMA Architects
        caption: Sept 2021 - Aug 2022
        description: |
         - Created detailed architectural plans and 3D models for residential projects
          
  - title: Certifications
    layout: list
    content:
      - layout: left
        #border: weak
        title: Google UX Design Certificate
        #link_text: Link Text
        #additional_links:
          #- title: Github page for project
            #icon: fab fa-github
            #url: https://github.com/example
        #quote: >
          #Short overview of the project
        description: |
         Completed training designed for entry-level job readiness. Topics included UX research fundementals, inclusive design, wireframes, low and high-fidelity prototypes.
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: MSc in Human-Computer Interaction
        sub_title: University of Patras
        #caption: Date Range (eg. 2016 - 2019)
        #quote: >
          #Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Excited to start this master program

      - layout: top-left
        title: Integrated Master in Architecture Engineering
        sub_title: Aristotle University of Thessaloniki
        #caption: Date Range (eg. 2016 - 2019)
        #quote: >
          #Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Trained in architectural design, learning to transform concepts into detailed plans while ensuring both form and function are optimized.

  - title: Skills
    layout: text
    content: |
      Figma • Adobe XD • Autocad • Rhino 3D • Adobe Photoshop • Adobe Indesign • HTML • CSS

      

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme
# remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"

